### ISSUE TITLE
Loading components from SpanXPathSelector

### ISSUE THREAD

**Issue by bloomonkey** [cheshire3/cheshire3#40]
Slightly paraphrased summary of the issue from email by @azaroth42 :

> In `cheshire3.documentFactory.ComponentDocumentStream` code assumes, naively and incorrectly, that itersiblings() will find always the end element. In the following example it doesn't, as it's not a sibling, instead it's nested inside another element.
> 
> ```
> <p>
>    <hr/>
>     <p>
>        <hr/>
>     </p>
> </p>
> ```
> 
> So I think it needs to `iter()` (in case it's nested) and then `itersiblings()` (as `<hr/>` in this case is empty) and then `iter()` down each sibling in turn?
> 
> But then making the actual XML string is trickier than just `etree.tostring()`.

**Comment by bloomonkey** [comment]
I can see why it's failing for your example but I can equally see the justification for using itersiblings (so as to guarantee well-formed components). What would you want to do if the end element was a sibling of the start element's parent? e.g.

```
<div>
  <p>
    <hr/>
    <p>
      ...
    </p>
  </p>
  <hr/>
</div>
```

I don't think that your proposal would work in these circumstances. To be as flexible as possible, it might need something like:

``` python
# Result of a SpanXPathSelector
doc = []
tree = d.getroottree()
root = tree.getroot()
started = False
for x in root.iter():
    if x == xp[0]:
        started = True
    elif x == xp[1]:
        break
    if started:
        # append serialized x to doc
docstr = ''.join(doc)
```

As you say, serializing the (SG|X)ML string will be tricker than just `etree.tostring()`, and any workaround is likely to complicated further by the possibility of namespaced XML...

**Comment by azaroth42** [comment]
Good points.

The result I'd like to see is:

All of the content between the two elements, with any required opening
tags at the beginning or closing tags at the end to make it
well-formed XML.

So your example would be

<p> 
  <p>
    ...
  </p>
</p>


This is relatively easy in SAX parsing, but a complete pain in DOM
walking.  Perhaps the easiest would be to re-parse the DOM as SAX?
Otherwise:

iter() down the current element.
while not end not found, then iter() down parent element of current
ignoring already processed.

eg:
phase 1:

<hr/>

phase 2:

<p> (skipping hr)
phase 3:
<div> (skipping p)
End when hit second hr

?

Rob

On Tue, Jun 26, 2012 at 4:31 AM, John Harrison
<reply@reply.github.com>
wrote:

**Comment by bloomonkey** [comment]
I'm wondering if the `iterwalk()` (http://lxml.de/parsing.html#iterwalk) method could be useful for walking `lxml.etree.Element`s in a SAX-like way.

Alternatively the document could be assembled as a list of strings, then parsed with the `lxml.html.fromstring()` or `lxml.html.soupparser.fromstring()` (http://lxml.de/elementsoup.html) to repair the resulting string into well-formed XML.

**Comment by azaroth42** [comment]
Good find. Looking at iterwalk() based implementation now.

R

On Tue, Jun 26, 2012 at 9:24 AM, John Harrison
reply@reply.github.com
wrote:

**Comment by azaroth42** [comment]
The following code works for my use case (TEI) and I believe works for
different levels of nesting. It doesn't process namespaces in the
rewriting. (Exercise for the reader :) )

``` python
                    # Result of a SpanXPathSelector (startNoe, endNode)
                    r = xp[0]
                    start = xp[0]
                    end = xp[1]

                    # ---- Non namespace version ----
                    doc = []
                    sancs = [x for x in start.iterancestors()]
                    eancs = [x for x in end.iterancestors()]
                    sancs.reverse()
                    eancs.reverse()
                    # Find common ancestor
                    x = 0
                    ls = len(sancs)
                    le = len(eancs)
                    while ls < x and le < x and sancs[x] == eancs[x]:
                        x+=1

                    prt = sancs[x]
                    recording = 0
                    open = []
                    closing = []

                    # walk events
                    for evt,elm in etree.iterwalk(prt, events=('start','end')):
                        if not recording and evt == 'start' and elm == start:
                            recording = 1
                        elif evt == 'start' and elm == end:
                            break
                        if recording:
                            if evt == 'start' and isinstance(elm.tag, str):
                                attrs = ' '.join(['%s="%s"' % x for x
in elm.attrib.items()])
                                if attrs:
                                    attrs = ' ' + attrs
                                doc.append("<%s%s>%s" % (elm.tag,
attrs, elm.text if elm.text else ""))
                                open.append(elm)
                            elif isinstance(elm.tag, str):
                                doc.append("</%s>%s" % (elm.tag,
elm.tail if elm.tail else ""))
                                if elm in open:
                                    open.remove(elm)
                                else:
                                    closing.append(elm)
                    # Close open things
                    open.reverse()
                    for elm in open:
                        doc.append("</%s>" % elm.tag)
                    # Open closed things
                    for elm in closing:
                        attrs = ' '.join(['%s="%s"' % x for x in
elm.attrib.items()])
                        if attrs:
                            attrs = ' ' + attrs
                        doc.insert(0, "<%s%s>%s" % (elm.tag, attrs,
elm.text if elm.text else ""))

                    # ----
```

**Comment by azaroth42** [comment]
Minor correction -- don't add text/tail when opening closed elements
at the end of the block. This probably isn't what is wanted for
indexing, as they're only being added for well-formedness

R

**Comment by bloomonkey** [comment]
I'm going to write some unittests for this now so that we can be sure that it works in all circumstances.

**Comment by bloomonkey** [comment]
@azaroth42 am I correct in assuming that startNode and endNode should be excluded from the resulting Documents? i.e. ComponentDocumentFactory configured with SpanXPathSelector configured with `<xpath>hr</xpath>`, loads:

```
<p>
    <hr/>
    <p>
        Some text.
    </p>
    <hr/>
</p>
```

Should result in Document with content:

```
<c3component ...>
<p>
    Some text.
</p>
</c3component>
```

**Comment by azaroth42** [comment]
Good question.  My use case is to include the start tag but not the
end tag.  Should probably go into a setting on SpanXPath ?

R

On Wed, Jun 27, 2012 at 6:36 AM, John Harrison
reply@reply.github.com
wrote:

**Comment by bloomonkey** [comment]
The SpanXPathSelector just selects pairs of start and end nodes. I think that the setting would have to go on the ComponentDocumentFactory in order for it to know what it should do when actually processing those pairs.

Proposal:

``` python
_possibleSettings = {
        'keepStart': {
            'docs': "Should the factory include the start tag of created component in the output Document. Default: yes",
            'type': int
        },
        'keepEnd': {
            'docs': "Should the factory include the end tag of created component in the output Document. Default: yes",
            'type': int
        },
    }
```

**Comment by azaroth42** [comment]
Yep, +1

R

On Wed, Jun 27, 2012 at 10:04 AM, John Harrison
reply@reply.github.com
wrote:

**Comment by bloomonkey** [comment]
Interesting... It seems like the cause of your initial problem might have been that SpanXPathSelector fails to select endNodes that are not direct siblings of the startNode.

This in turn appears to be due to a bug (?) in lxml Element's xpath method:

``` python
>>> from lxml import etree
>>> xml = etree.XML('<foo><baz/><bar><baz/></bar></foo>')
>>> xml.xpath('baz')
[<Element baz at 0xb746c1bc>]
>>> xml.xpath('//baz')
[<Element baz at 0xb746c1bc>, <Element baz at 0xb746c194>]
```

Of course even if it had, the ComponentDocumentFactory would likely have generated incorrect Documents...
