### ISSUE TITLE
Cannot merge bitmap index results

### ISSUE THREAD

**Issue by azaroth42** [cheshire3/cheshire3#41]
Traceback (most recent call last):
  File "./run.py", line 39, in <module>
    rs = db.search(session, q)
  File "../../code/cheshire3/database.py", line 280, in search
    rs = self._search(session, query)
  File "../../code/cheshire3/database.py", line 252, in _search
    rs = new.combine(session, [left, right], query, self)
  File "../../code/cheshire3/resultSet.py", line 694, in combine
    if o.fromStore:
AttributeError: 'BitmapResultSet' object has no attribute 'fromStore'

Yes, I know that I wrote this code and that it has never worked properly when merging between different stores! Mea culpa!
But would still like it fixed :D

Also ... any doesn't seem to work?

> > > q = parse('c3.idx-col any "a b"')
> > > rs = db.search(session, q)
> > > len(rs)
> > > 0
> > > q = parse('c3.idx-col = a')
> > > rs = db.search(session, q)
> > > len(rs)
> > > 12551

**Comment by bloomonkey** [comment]
Merging BitmapResultSet with SimpleResultSet might have to wait until after 1.0 release (end of July hopefully)

'any' doesn't seem to work specifically on BitMapIndex or more generally?

**Comment by azaroth42** [comment]
Actually just adding an empty fromStore property to BitmapResultSet
seems to work?

Any fails only on bitmaps. Non bitmap idx:

> > > q = parse('c3.idx-text-kwd any "aventures paris"')
> > > 
> > > rs = db.search(session, q)
> > > len(rs)
> > > 318
> > > q = parse('c3.idx-text-kwd any "paris"')
> > > rs = db.search(session, q)
> > > len(rs)
> > > 302
> > > q = parse('c3.idx-text-kwd any "aventures"')
> > > rs = db.search(session, q)
> > > len(rs)
> > > 16

On Wed, Jun 27, 2012 at 10:14 AM, John Harrison
reply@reply.github.com
wrote:

**Comment by bloomonkey** [comment]
Phew, that is a relief :)

Will add the empty fromStore property for now. If anything more
sophisticated is needed it'll have to wait a little while.

**Comment by bloomonkey** [comment]
Fixed by commit edb919a179eafc19cea035df0faa68bba7fe7ec9

BitmapIndex 'any' search issue reported separately as #42
